// Generated by gir (https://github.com/gtk-rs/gir @ a97e6087cf6b)
// from /__w/gtuber/gtuber/x86_64-redhat-linux/gtuber (@ 4b1a0a3e285e)
// from /usr/local/share/gir-1.0 (@ ???)
// from /usr/share/gir-1.0 (@ ???)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "GtuberAdaptiveStreamManifest", sizeof(GtuberAdaptiveStreamManifest), alignof(GtuberAdaptiveStreamManifest));
    printf("%s;%zu;%zu\n", "GtuberClientError", sizeof(GtuberClientError), alignof(GtuberClientError));
    printf("%s;%zu;%zu\n", "GtuberFlow", sizeof(GtuberFlow), alignof(GtuberFlow));
    printf("%s;%zu;%zu\n", "GtuberManifestGeneratorError", sizeof(GtuberManifestGeneratorError), alignof(GtuberManifestGeneratorError));
    printf("%s;%zu;%zu\n", "GtuberStreamMimeType", sizeof(GtuberStreamMimeType), alignof(GtuberStreamMimeType));
    printf("%s;%zu;%zu\n", "GtuberWebsiteError", sizeof(GtuberWebsiteError), alignof(GtuberWebsiteError));
    return 0;
}
